services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - sms_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  sms_postgres: