spring:
  application:
    name: sms-gateway

  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/sms}
    username: ${R2DBC_USERNAME:user}
    password: ${R2DBC_PASSWORD:password}

  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:5432/sms
    locations: classpath:db/migration

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

jwt:
  private-key: ${JWT_PRIVATE_KEY:classpath:jwt/app.key}
  public-key: ${JWT_PUBLIC_KEY:classpath:jwt/app.pub}
  ttl: ${JWT_TTL:15m}

email-verification:
  base-url: http://localhost:8080/api/auth/email/verify?uid=%s&t=%s
  required: true

otp:
  email-verification:
    cache-prefix: otp:email-verification:%s
    ttl: 5m
    characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
    length: 50

management:
  health:
    redis:
      enabled: false
